// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";

type RouteParams<Route extends AppRoutes | LayoutRoutes> = {
  params: Promise<ParamMap[Route]>;
} & Record<string, unknown>;

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<RouteParams<Route>>
    | ((
        props: RouteParams<Route>
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<ParamMap[Route][]> | ParamMap[Route][];
  generateMetadata?: (
    props: RouteParams<Route>,
    parent: ResolvingMetadata
  ) => Promise<unknown> | unknown;
  generateViewport?: (
    props: RouteParams<Route>,
    parent: ResolvingViewport
  ) => Promise<unknown> | unknown;
  metadata?: unknown;
  viewport?: unknown;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<ParamMap[Route][]> | ParamMap[Route][];
  generateMetadata?: (
    props: RouteParams<Route>,
    parent: ResolvingMetadata
  ) => Promise<unknown> | unknown;
  generateViewport?: (
    props: RouteParams<Route>,
    parent: ResolvingViewport
  ) => Promise<unknown> | unknown;
  metadata?: unknown;
  viewport?: unknown;
};

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
  const handler = {} as typeof import("../src/app/(site)/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import("../src/app/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
