import type { Metadata } from "next";
import { font, fontMono } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} ${fontMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
